### PR TITLE
add yard, initial documentation comments

### PR DESCRIPTION
**Pull request by agaurav77**
Should be an okay-ish start for documentation.

#319

### CODE REVIEW

**Comment by claudijd** [comment]
@agaurav77 nice comments, I don't think this is in YARD format, please see recent PR from me with example of YARD format.

**Comment by claudijd** [comment]
See https://github.com/mozilla/ssh_scan/pull/311/files for guidance on YARD format

**Comment by agaurav77** [comment]
@claudijd 

Updated the PR, please review. Wasn't sure of yard syntax at some places, if I'm wrong, please point it out. Thanks!

`yardoc && yard server` should start a local documentation server.

**Comment by claudijd** [comment]
LGTM!

**Pull request merged**
