### PR TITLE
Fixed port issue

### PR DESCRIPTION
**Pull request by jinankjain**
@claudijd  @agaurav77  Fixed that port issue by overwriting ports with what is specified in -p

### CODE REVIEW

**Comment by jinankjain** [comment]
For more clarity 

-t github.com:22 -p 33,3333 final output github.com:33, github.com:3333
Same is true for -f flag too

This solves all the confusion

**Comment by claudijd** [comment]
@jinankjain if we're going to bury the :22 input, I don't think it should be silent.  I think this should throw an error.

**Comment by jinankjain** [comment]
@claudijd So we throw an error message stating that port 22 is rejected?

**Comment by claudijd** [comment]
@jinankjain I was thinking more a generic hard failure... -t flag with socket target + -p flags are incompatible

**Comment by jinankjain** [comment]
Okay cool that's kind of easy to do. I will update the patch soon

**Comment by jinankjain** [comment]
@claudijd Updated the patch

**Pull request merged**
