### PR TITLE
Testing coveralls

### PR DESCRIPTION
**Pull request by royalharsh**
Testing coveralls.

### CODE REVIEW

**Comment by rishabhs95** [comment]
Is coveralls posting the correct coverage report here?
I think it's not summarizing the report, rather it is posting for every matrix component.

**Comment by royalharsh** [comment]
Yeah, it is posting for every matrix component. But, the coverage is correct.

**Comment by rishabhs95** [comment]
Yeah, I meant is it right to post 5 individual posts for every push?
The readme tag will work right but PR should only get 1 coverall comment.

**Comment by royalharsh** [comment]
I know it's a bit noisy. One thing we can do is that we can run coveralls only on one version of ruby. Another thing we can do is that we can turn off commenting on pull requests.

**Comment by rishabhs95** [comment]
Yeah, I think checking coverage on the latest ruby version should work as if the tests are passing coverage won't depend upon the ruby version.

**Comment by claudijd** [comment]
@rishabhs95 I agree with the latest ruby approach, I think commenting, assuming it's only one comment per push is acceptable noise level.  Nice work here!

**Pull request merged**
