### PR TITLE
take out host key fingerprinting from scan_engine

### PR DESCRIPTION
**Pull request by agaurav77**
For #84.

I had some doubts on how to generate the ECDSA fingerprints, so didn't push that change in this PR.

### CODE REVIEW

**Comment by agaurav77** [comment]
@claudijd Please review

**Comment by claudijd** [comment]
@agaurav77 nice job with this, I think we should create some unit-tests around this newly created abstraction.  This is something we weren't able to do before because it wasn't abstracted out.

**Comment by agaurav77** [comment]
@claudijd Should I add more examples?

**Comment by claudijd** [comment]
@agaurav77 nice job here!

**Pull request merged**
