### PR TITLE
Initial prototype for queueing engine

### PR DESCRIPTION
**Pull request by royalharsh**
https://github.com/mozilla/ssh_scan/issues/49  @claudijd Any thoughts?

### CODE REVIEW

**Comment by royalharsh** [comment]
I think there's room for improvement.

**Comment by claudijd** [comment]
@pwnbus @claudijd @gdestuynder review

**Comment by claudijd** [comment]
Is this PR superceded by #259

**Comment by claudijd** [comment]
Closed in favor of #259

**Pull request closed without merging**
