### PR TITLE
Add binaries release pipeline via travis

### PR DESCRIPTION
**Pull request by rishabhs95**
Adds a task for building and releasing binaries with every new release(tag) push.
following Issue #201.

### CODE REVIEW

**Comment by claudijd** [comment]
@rishabhs95 thanks for this, I think I'll need to work with a GitHub admin to help setup the OAUTH token.  @gdestuynder would you be able to assist us with getting this?

**Comment by claudijd** [comment]
I'd like to close this PR, as I'm not really sure we're going to be ready for this in the near term.

**Comment by rishabhs95** [comment]
Ok cool, no worries :)

**Comment by gdestuynder** [comment]
sorry i did not see the notification initially (month-s ago.. argh)
i can absolutely help with oauth tokens if that's needed in the future

**Pull request closed without merging**
