### PR TITLE
Add Jinak Jain as an author

### PR DESCRIPTION
**Pull request by claudijd**
@jinankjain has been super active on this project and I feel like it's only fair to list him now as an official author of this project.

### CODE REVIEW

**Comment by claudijd** [comment]
@jinankjain I've also granted you commit writes on the project so you can merge your own fixes and help other land their code.

**Comment by jinankjain** [comment]
@claudijd Thanks for the access 😄

**Comment by claudijd** [comment]
@jinankjain no problem, you've earned it.

**Comment by claudijd** [comment]
@jinankjain you should be able to see the draft release notes for 0.0.11, feel free to add any call outs, but I'd like to hold actual release until Wednesday for predictability.

**Comment by claudijd** [comment]
@jinankjain would you also mind doing a couple extra things now that you've got commit rights just to help ensure ssh_scan stays safe?

1.) Make sure your GitHub account has 2FA enabled (https://help.github.com/articles/securing-your-account-with-two-factor-authentication-2fa/)
2.) Add your GPG key to GitHub and do signed commits/merges so they show as verified (https://github.com/blog/2144-gpg-signature-verification)

**Comment by jinankjain** [comment]
@claudijd I already have a two factor authentication enabled and I would add my GPG keys to Github soon. 😄

**Comment by claudijd** [comment]
@jinankjain perfect, thank you!

**Pull request merged**
