### PR TITLE
Add coveralls

### PR DESCRIPTION
**Pull request by royalharsh**

### CODE REVIEW

**Comment by royalharsh** [comment]
How about this @rishabhs95 ?

**Comment by royalharsh** [comment]
I think this should do it.

**Comment by rishabhs95** [comment]
No, I dont think it's sending the correct coverage yet.

**Comment by rishabhs95** [comment]
You've integrated coverage for your fork whereas travis is running on `mozilla/ssh_scan`, this will never update your coverage. Even after you activate travis on your fork, travis will never send the correct coverage for that, because our travis tests works correctly with PRs whereas, we generally don't create a PR on our fork.

 Also, if anyone sends a PR on `mozilla/ssh_scan`, the new coverage report won't be generated this way, for that you need to activate coveralls on `mozilla/ssh_scan`.

**Comment by royalharsh** [comment]
Yeah, realized that after you merged it. https://github.com/mozilla/ssh_scan/pull/317

**Comment by royalharsh** [comment]
Fixed.

**Pull request merged**
